apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: windowsmachineconfigs.wmc.openshift.io
spec:
  group: wmc.openshift.io
  names:
    kind: WindowsMachineConfig
    listKind: WindowsMachineConfigList
    plural: windowsmachineconfigs
    singular: windowsmachineconfig
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: WindowsMachineConfig is the Schema for the windowsmachineconfigs
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: WindowsMachineConfigSpec defines the desired state of WindowsMachineConfig
          properties:
            aws:
              description: AWS holds AWS specific cloud provider information
              properties:
                credentialAccountId:
                  description: CredentialAccountID is account id associated with AWS
                    provider
                  type: string
                sshKeyPair:
                  description: SSHKeyPair is the sshKeyPair associated with cloudprovider.
                    AWS asks a keypair to be present for encrypting the Windows VM
                    password
                  type: string
              required:
              - credentialAccountId
              - sshKeyPair
              type: object
            azure:
              description: Azure holds Azure specific cloud provider information
              type: object
            instanceType:
              description: InstanceType represents the flavor of instance to be used
                while creating the virtual machines. Please note that this is common
                across all the Windows nodes in the cluster
              type: string
            replicas:
              description: Replicas represent how many Windows nodes to be added to
                the OpenShift cluster
              minimum: 0
              type: integer
          required:
          - instanceType
          - replicas
          type: object
        status:
          description: WindowsMachineConfigStatus defines the observed state of WindowsMachineConfig
          properties:
            conditions:
              description: Conditions states the latest available observations of
                current state
              items:
                properties:
                  lastTransitionTime:
                    description: LastTransitionTime is the timestamp corresponding
                      to the last status change of this condition
                    format: date-time
                    type: string
                  message:
                    description: Message is the human readable reason for the condition
                      change
                    type: string
                  reason:
                    description: Reason is the machine readable reason for the condition
                      change
                    type: string
                  status:
                    description: Status of the condition
                    type: string
                  type:
                    description: Type describes the type of the condition
                    type: string
                required:
                - lastTransitionTime
                - status
                - type
                type: object
              type: array
            joinedVMCount:
              description: JoinedVMCount is the number of VMs that successfully joined
                the cluster
              type: integer
          required:
          - conditions
          - joinedVMCount
          type: object
      required:
      - spec
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
