apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows-machine-config-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: windows-machine-config-operator
  template:
    metadata:
      labels:
        name: windows-machine-config-operator
    spec:
      serviceAccountName: windows-machine-config-operator
      volumes:
      # TODO: Remove the cloud-credentials and cloud-private-key volumes as part of
      # https://issues.redhat.com/browse/WINC-325
      - name: cloud-credentials
        secret:
          secretName: cloud-credentials
      - name: cloud-private-key
        secret:
          secretName: cloud-private-key
      # TODO: Remove the kubeconfig volume as part of https://issues.redhat.com/browse/WINC-328
      - name: kubeconfig
        secret:
          secretName: kubeconfig
      containers:
        - name: windows-machine-config-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - windows-machine-config-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "windows-machine-config-operator"
            # TODO: Remove the KUBECONFIG environment variable as part of https://issues.redhat.com/browse/WINC-328
            - name: KUBECONFIG
              value: /etc/kubeconfig/kubeconfig
          volumeMounts:
          # TODO: Remove the cloud-credentials and cloud-private-key volumeMounts as part of
          # https://issues.redhat.com/browse/WINC-325
          - name: cloud-credentials
            mountPath: "/etc/cloud/"
            readOnly: true
          - name: cloud-private-key
            mountPath: "/etc/private-key/"
            readOnly: true
          # TODO: Remove the kubeconfig volumeMount as part of https://issues.redhat.com/browse/WINC-328
          - name: kubeconfig
            mountPath: "/etc/kubeconfig/"
            readOnly: true
