apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: windows-machine-config-operator
  namespace: openshift-windows-machine-config-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: windows-machine-config-operator
  source: wmco
  sourceNamespace: openshift-marketplace
  startingCSV: windows-machine-config-operator.v0.0.0
